### ISSUE TITLE
Juniper configuration download failed when using apply-groups in config

### ISSUE THREAD

**Issue by riddler63** [rconfig/rconfig#90] opened 2023-11-02 08:42 UTC
**Describe the bug**
Juniper full configuration download failed when using apply-groups

**To Reproduce**
Create Juniper switch configuration with groups, like:

`groups {
    GR-IRB-ACCESS-INTF {
        interfaces {
            <irb*> {
                unit <*> {
                    family inet {
                        rpf-check;
                        mtu 9116;
                    }
                }
            }
        }
    }
    GR-ACCESS-INTF {
        interfaces {
            "<[aegx][et]*>" {
                mtu 9216;
                hold-time up 2500 down 0;
                unit 0 {
                    family ethernet-switching {
                        storm-control SC-ACCESS;
                    }
                }
            }
            "<[ex][et]*>" {
                ether-options {
                    no-flow-control;
                }
            }
            <ae*> {
                aggregated-ether-options {
                    no-flow-control;
                    lacp {
                        active;
                        periodic fast;
                    }
                }
            }
        }
    }
}
`

**Expected behavior**
Full configuration backup by using command "show configuration"

**Screenshots**
![image](https://github.com/rconfig/rconfig/assets/32638959/def2a63a-8f83-4316-8835-e18b7a8cecb0)

**rConfig Version Information (You can copy this from the rConfig dashboard):**
OS VERSION
Rocky  9.2 (Blue Onyx)
PHP / LARAVEL VERSION
8.2.12 / 10.22.0
REDIS VERSION
6.2.7
MYSQL VERSION
10.5.22 

**Logs info (can be retrieved from /var/www/html/rconfig6/storage/logs - try to paste relevant logs only)
There are no logs at /var/www/html/rconfig6/storage/log

**Additional context**
Assumption: There is a "*" which hampers full configuration backup.

**Comment by stephenstack** [comment] 2023-11-05 21:21
Thats a very hard stop i.e. the location of the wherethe config download stops. Its quite unusual. 
The first thing I would ask is, what is the devices 'prompt' set to in the device settings?

**Comment by stephenstack** [comment] 2023-11-05 21:21
Thats a very hard stop i.e. the location of the wherethe config download stops. Its quite unusual. 
The first thing I would ask is, what is the devices 'prompt' set to in the device settings?

**Comment by riddler63** [comment] 2023-11-06 06:52
Hello,

The device name is `username@QFX-5120-1>` and "Main Prompt" is set to ">", "Enable Prompt" is empty. 

So rConfig waits for particular line, such as "QFX-5120-1>" to detect the end of the configuration?

**Comment by stephenstack** [comment] 2023-11-20 06:04
Hi,

Sorry for the delay in response, we are working hard on V7 pro. Was this ever resolved?

**Comment by stephenstack** [comment] 2023-12-05 09:21
Hi, if you can provide an update, please do, otherwise I'll go ahead and close this.

See some extra troubleshooting steps below.

Usually this can be caused by a timeout issue, or a prompt misconfiguration issue. Steps to troubleshoot are

Change connection template timeout to 5 seconds
Change prompt to .*# or '.> which is a regex wildcard up to the end of the prompt.
Run the manual debug, see docs https://docs.rconfig.com/general/troubleshooting#rconfig-command-line-tools
If you can, share the output form the debug, and that might help identify the issue.

Check out the vids below
https://youtu.be/h0egZhKmuUw?si=gn_cCDkosqOfMO0Q
https://youtu.be/gu9yuvjvzUQ?si=3BSAPVN9VXnC5hVu

**Comment by stephenstack** [comment] 2023-12-06 09:17
Closing due to inactivity

**Closed as completed by stephenstack** 2023-12-06 09:17 UTC
