### ISSUE TITLE
Existing apache settings overwritten

### ISSUE THREAD

**Issue by rsaeks** [rconfig/rconfig#28] opened 2016-11-01 14:39 UTC
If existing apache settings are present the rconfig config replaces those, rather than adding to the httpd.conf.d directory with a product-specific configuration. It would be nice to see a note in the documentation about this, have a rconfig.conf apache config put into a conf.d directory or prompt about the scenario prior to install.

**Comment by rconfig** [comment] 2017-06-11 03:27
rConfig is designed to be standalone on the server which it is installed. You should not run any other sites with it. Closing this as this is by design

**Closed by rconfig** 2017-06-11 03:27 UTC
